### ISSUE TITLE
Knockout Recently Viewed contains wrong product url (with category path), also not correct url <meta property="og:url"> on product view page

### ISSUE THREAD

**Issue by novakivskiy** [magento/magento2#13227]
### Preconditions

1. Magento 2.2.2
2. PHP 7

I added "Recently Viewed" to the product page. Using  xml layout
```
 <referenceContainer name="content.aside">
            <block class="Magento\Catalog\Block\Widget\RecentlyViewed" name="recently_viewed" template="Magento_Catalog::product/widget/viewed/grid.phtml" after="-">
                <arguments>
                    <argument name="uiComponent" xsi:type="string">widget_recently_viewed</argument>
                    <argument name="page_size" xsi:type="number">4</argument>
                    <argument name="show_attributes" xsi:type="string">name,image,price</argument>
                    <argument name="show_buttons" xsi:type="string">add_to_cart,add_to_compare,add_to_wishlist</argument>
                </arguments>
            </block>
        </referenceContainer>
```

### Steps to reproduce

1. Site use product configuration "Use Categories Path for Product URLs" = NO
2. Open several products to fill history of the products viewed
3. On any page of the site, open  page inspector(web developer utility)  and see the local storage cache "product_data_storage", find product contain url with category path (http://take.ms/ukxAM).
Or   open  source code html of product view page, and find the next code  js component "Magento_Catalog/js/product/view/provider".

Example:
```
<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Catalog/js/product/view/provider": {
                    "data": {"items":{"720" , ... {"url":"http:\/\/m2-sample.dev\/catalog\/product\/view\/id\/720\/s\/tiberius-gym-tank\/category\/13\/","id":720,"name":"Tiberius Gym Tank" ....    }
        }
    }
</script>
```

UPD:
Another way to proset the error:
1. open product view page
2. open source html page
3) find tag <meta property="og:url" content="
4) my result
page url - http://m2-sample.dev/montana-wind-jacket.html, tag - `<meta property="og:url" content="http://m2-sample.dev/men/tops-men/jackets-men/montana-wind-jacket.html" />`

### Expected result

1. URL should not contain a category path (http://m2-sample.dev/tiberius-gym-tank.html)

### Actual result

1. ![image](https://user-images.githubusercontent.com/971021/35011272-385f0ce6-fb0e-11e7-8983-d72207454c1e.png)

**Comment by novakivskiy** [comment]
if I activate the configuration "Use Canonical Link Meta Tag For Products = YES", 
then the tag will be added to the page `<link  rel="canonical"> </link>` (program code https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Block/Product/View.php, 153 line ). But this is not logical behavior, because I have a configuration "Use Categories Path for Product URLs = NO"

**Comment by magento-engcom-team** [comment]
@novakivskiy, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @vshatylo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by atishgoswami** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@atishgoswami thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @novakivskiy. Thank you for your report. 
The issue has been fixed in magento/magento2#22650 by @atishgoswami in 2.3-develop branch
Related commit(s):
 - [50d8546617115c3daedeff78af318849acb9c1cf](https://github.com/magento/magento2/commit/50d8546617115c3daedeff78af318849acb9c1cf)
 - [d254b9f1b8bd4ae557d0dc2308aa9f79af96289b](https://github.com/magento/magento2/commit/d254b9f1b8bd4ae557d0dc2308aa9f79af96289b)

The fix will be available with the upcoming 2.3.3 release.
