### ISSUE TITLE
Order of catalog images not respected on store view level

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#14208]
I don't know whether this is a feature or a bug, it's a quite unpleasant effect, the order of the images in the gallery is not respected when a product is saved on storeview level. 

### Preconditions

1. Magento 2.2.2

### Linked issues:
https://github.com/magento/community-features/issues/23
### Steps to reproduce

1. Go to product that has multiple images 
2. set scope to all storeviews
3.  change the first image in the gallery 
4. save the product
5. switch to store view scope (notice that the image order is correct, for now)
6. save the product
7. switch back to all store views 
8. change the order of the images again 
9. save the product
10. go back to storeview scope
11. notice that the order of the images is not correct anymore.

There should be some sort of 'use default value' checkbox for the media gallery, or at least for the position.

### Expected result

1. The image positions should be according the 'All store views'

### Actual result

1. The image positions use there own position, copied from the 'all storeviews', and don't change anymore according to the 'all store views'

**Comment by magento-engcom-team** [comment]
@duckchip, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by febinthomas** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@febinthomas thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by barathdckap** [comment]
I want to work on this #MM19IN

**Comment by magento-engcom-team** [comment]
@barathdckap thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @barathdckap. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by barathdckap** [comment]
@duckchip The bug you reported is not an issue rather it is a feature. I would like to give more insights into what happening when we change the position of the image,
When we follow the steps 1,2,3 and 4(please refer the steps to reproduce points), a new record will be created or updated(if already exists) with the position values for the default store view (in my case "store_id" is 0) in the 'catalog_product_entity_media_gallery_value' table. Thus the updated position will be reflected in the Magento backend by referring to the mentioned table.

![imageedit_9_2674091309](https://user-images.githubusercontent.com/43631763/52345895-4f69fe80-2a44-11e9-80fa-da728ed7a3ab.gif)

When you switch to different store view((in my case "store_id" is 1), the system will look for the image position for the respected store view("store_id" 1) from 'catalog_product_entity_media_gallery_value' table. If the value is found then the corresponding position value for the store view will be returned else the position of the default store view will be used.

Before doing the Step 6, the position for the store view is not found in the table thus it was using the default store view position. After doing step 6, a new record with the updated position for the store view(id 1) will be created. Thus it will be used from now on.

![store_id_2](https://user-images.githubusercontent.com/43631763/52345530-7c69e180-2a43-11e9-90de-eba8d12b7a38.gif)

So what's happening is intended behavior, not an issue. Thus I'm closing this ticket out.

**Comment by hostep** [comment]
@barathdckap: I think the bug report is valid, because there is no user interface which indicates that the positions of images are storeview specific.
I think it's ok if they are storeview specific, but then there should be some kind of UI to remove the storeview specific positions and use the ones from the 'All Storeviews', just like we have for other attributes like 'Description' or 'Product Name' provided by the checkbox 'Use Default Value'.

Do you agree on this?

*Update*: it looks like there is a PR addressing this problem: https://github.com/magento/magento2/pull/18778

**Comment by barathdckap** [comment]
@hostep I agree with you and I have viewed the PR and it seems it will be released in Magento 2.3.1
