### ISSUE TITLE
complete support for modules outside of app/code/

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#1660]
follow up issue to #1013 this time to make sure *everything* works, as people reported #1206 is incomplete.  
Community driven Issue.  

Collects all the seperate Issues and *maybe Issues* which should be Tested

Issues:  

-  [x] files in `var/generation/` are not generated (solved by #1659)
-  [x] `etc/adminhtml/system.xml` is not loaded (probably solved by #1709)

Things which should get tested:  

- [ ] email templates
- [ ] `\Magento\Framework\Module\Dir\Reader` (loading of composer.json) (maybe solved by #1490 )
- [ ] all related to `\Magento\Framework\View\Design\Fallback\RulePool`
  - [ ] email templates
  - [ ] dynamic view files
  - [ ] template files
  - [ ] static view files, such as CSS, JavaScript, images
- [ ] `DiCompileMultiTenantCommand`

Magento Internal parts which may not Work if placed outside of `app/code/`:  

a lot of them make use of `$filesystem->getDirectoryRead(DirectoryList::MODULES)` where Iam not sure how it works/acts.

- [ ] ImportExport
  - [ ] `\Magento\ImportExport\Controller\Adminhtml\Import\Download`
- [ ] `\Magento\PageCache\Model\Config` (reading of vcl file)
- [ ] `\Magento\Paypal\Block\Iframe`
- [ ] `\Magento\Persistent\Model\Persistent\Config`
- [ ] `DependenciesShowFrameworkCommand`
- [ ] `\Magento\Setup\Model\SampleData`

**Comment by joshdifabio** [comment]
Great job. 

See also #1481 and [@vrann's update](https://github.com/magento/magento2/pull/1490#issuecomment-130467497) regarding this.

**Comment by Vinai** [comment]
Very cool! I'm sorry I'm on vacation right now and can't check out the branch and play with it. Looking forward to it once I'm back end of August.

**Comment by vrann** [comment]
- [ ] Unit tests run the tests from vendor
- [ ] It is possible to locate xsd files to do validation and to reference from xml
- [ ] magento2-base component is removed. Project structure should be defined in magento/magento2-community-edition, integration tests, libraries, etc should have own components

**Comment by piotrekkaminski** [comment]
@buskamuza hey, did the recent changes solved this issue?

**Comment by dfediuk** [comment]
For now a custom extension can reside in the `vendor` folder but it does not work for translation packages because the system looks for them in `app/i18n` folder.

**Comment by buskamuza** [comment]
@dfediuk , could you, please, point to the code that searches in `app/i18n`? Thanks.

**Comment by Flyingmana** [comment]
I close this issue, as the basic stuff now works for me
