### ISSUE TITLE
GA Not Tracking related to Magento v 2.2.5???

### ISSUE THREAD

**Issue by NoMagentoSupportQuestionMark** [magento/magento2#18167]
Hi GitHub Users,  2 questions:

1) First Off, Is there really no Magento-Support ticketing system?  If there is, I couldn't find it.

2) Our magento-store has not had GA-tracking for the last month.  (which appears to correlate with our upgrade to Magento v.2.2.5 ) 

Is there a wide-spread, known-issue with GA not working related to Magento v 2.2.5?

And if so, is there a known fix that you can share instructions for?

Thank-you!

**Comment by magento-engcom-team** [comment]
Hi @NoMagentoSupportQuestionMark. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@NoMagentoSupportQuestionMark do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
@NoMagentoSupportQuestionMark (funny name :p): have you tried searching on github first? There are some reports, maybe you can find answer in those?
https://github.com/magento/magento2/search?q=2.2.5+google+analytics&type=Issues

This one comes to mind: https://github.com/magento/magento2/issues/14951, it reports an issue where the conversions aren't tracked anymore, but that already started happening in 2.2.4 and should be fixed in 2.2.6

Not sure if this answers helps.

But I'm going to close this issue, as this is not a real bug report, feel free to use the search in github, or ask your question on https://magento.stackexchange.com/ or on https://community.magento.com/ which are better places for these kind of questions.
