### ISSUE TITLE
When installing Magento 2.3.0 Strorefront and Admin URLs throw a 404 if "localhost" is used.

### ISSUE THREAD

**Issue by thesurenk** [magento/magento2#20355]
While installing (web setup) Magento 2.3.0, if we choose *localhost*, the URL's (Storefront and Admin) throw a *404 error messages*. But if we choose *127.0.0.1*, the URLs (Storefront and Admin) load without errors.

- Does not work:
   - http://localhost:8081/magento2/
   - http://locahost:8081/magento2/admin_2lecxk/ 
- Works:
   - http://127.0.0.1:8081/magento2/
   - http://127.0.0.1:8081/magento2/admin_2lecxk/

Please note using custom port `8081` and not `8080`.

### Preconditions (*)

1. macOS Mojave 10.14.2
2. Apache 2.4.37
3. PHP 7.2.9
4. MySQL 8.0

### Steps to reproduce (*)

**Part 1**
1. Download a new copy of Magento 2.3.0 from https://magento.com/tech-resources/download choosing *Magento Open Source 2.3.0 Wioth Sample Data.zip*
2. Unzip and copy to Apache's htdocs folder
3. Give Write permissions recursively on the *magento2* folder 
4. Restart Apache
5. Install using `http://localhost:<custom port>/magento2/setup`
6. At 3rd step : Web Configuration, while entering "Your Store Address", use *localhost* (any custom port). 
7. After install you will see the URLs to Storefront and Admin (as below).
8. Try accessing the Storefront and Admin URL's, they show 404/Not found
![screen shot 2019-01-16 at 2 45 37 pm copy](https://user-images.githubusercontent.com/902972/51285197-c6672680-19b3-11e9-8e38-0fbd71e09178.png)

**Part 2**
9. Repeat above steps 1 to 5
10. At 3rd step : Web Configuration, while entering "Your Store Address", replace localhost with 127.0.0.1 (any custom port). 
11. After install you will see the URLs to Storefront and Admin (as below).
12. Try accessing the Storefront and Admin URL's, they will load properly.
![screen shot 2019-01-16 at 5 03 07 pm](https://user-images.githubusercontent.com/902972/51285319-0e864900-19b4-11e9-9e99-eb32b3e8ed41.png)

### Expected result (*)

1. Storefront URL, if users choose `localhost` as `http://locahost:<any port>/<store name>` should load without 404 errors.
![screen shot 2019-01-16 at 4 57 23 pm](https://user-images.githubusercontent.com/902972/51284644-dbdb5100-19b1-11e9-968b-149b31aa5626.png)

2. Admin URL, if users choose `localhost` as `http://locahost:<any port>/<store name>/admin` should load without 404 errors.
![screen shot 2019-01-16 at 4 57 58 pm](https://user-images.githubusercontent.com/902972/51284640-d7169d00-19b1-11e9-8894-25e0d5285fc9.png)

### Actual result (*)

1. Storefront URL, if users chooses `localhost` as `http://locahost:<any port>/<store name>` should load without 404 errors.
![screen shot 2019-01-16 at 3 44 17 pm](https://user-images.githubusercontent.com/902972/51284882-b3078b80-19b2-11e9-8d5b-54642455ab96.png)

2. Admin URL, if users chooses `localhost` as `http://locahost:<any port>/<store name>/admin` should load without 404 errors.

**Comment by magento-engcom-team** [comment]
Hi @ksurendra. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ksurendra do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by thesurenk** [comment]
@cedarvinda it took me more than 20 mins to write up the issue and strangely it closed in 13 mins. Was this tested on macOS Mojave? Apache? PHP 7.2? 

Can you add some screenshots of localhost working for you?

**Comment by irajneeshgupta** [comment]
@ksurendra Hi, can you confirm that your host file is correct? 
![host-file-mac-screenshot-04](https://user-images.githubusercontent.com/18143480/51299466-991b8680-1a4e-11e9-8ae3-244431a65045.jpg)

**Comment by thesurenk** [comment]
@irajneeshgupta  Yes
![screen shot 2019-01-17 at 10 36 02 am](https://user-images.githubusercontent.com/902972/51333612-beef5e00-1a43-11e9-9015-4fb3d737b9a8.png)

My puzzle was that storefront & admin works with `127.0.0.1` but not with `localhost`. While all other pages/sites on apache work at `localhost\xxx`
