### ISSUE TITLE
 Meta Keywords/Meta Description are input field in product form while they are defined as textarea

### ISSUE THREAD

**Issue by amitvishvakarma** [magento/magento2#20555]
**Preconditions**

In Magento 2.2.x and Magento 2.3.x, the Meta Keywords, Meta Description are of Textarea defined in product attributes, but they are showing input [type = text ] in product form.

**Steps to reproduce**
    

1. Go to Store->Attributes->Product.
2. Search for Meta Keywords/Meta description.
3. View them, you will able to see their \'Catalog Input Type for Store Owner\' is Textarea.
4. Now go to Catalog->Product
5. Click on \'Add Product button\' Or Edit Product.
6. Go to Search engine optimization tab.
7. You will see Meta Keywords/Meta description are showing text field instead of textarea.

**Expected result**

They must show <textarea>

**Actual result**

They are showing of input [type="text"]

**Images**
![meta_description](https://user-images.githubusercontent.com/25526499/51657058-3b94b600-1fc9-11e9-937e-55a232c35109.png)
![meta_keywords](https://user-images.githubusercontent.com/25526499/51657059-3b94b600-1fc9-11e9-9485-854f35299e34.png)
![meta frontend input in database](https://user-images.githubusercontent.com/25526499/51657060-3c2d4c80-1fc9-11e9-8fd5-97fb64fa891e.png)
![input field in product form](https://user-images.githubusercontent.com/25526499/51657062-3c2d4c80-1fc9-11e9-8107-1fd46abbeb23.png)

**Comment by magento-engcom-team** [comment]
Hi @amitcedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amitcedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @jitendra-cedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@jitendra-cedcoss Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97903`, `MAGETWO-97904` were created

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amitcedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20556 by @amitcedcoss in 2.3-develop branch
Related commit(s):
 - [a5dfa0dcf58e2a95dd0aa953b890154922efb74a](https://github.com/magento/magento2/commit/a5dfa0dcf58e2a95dd0aa953b890154922efb74a)

The fix will be available with the upcoming  release.

**Comment by magento-engcom-team** [comment]
Hi @amitcedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#21199 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [b86a3940282b558ecb0363b990b6ff3dc41a61d0](https://github.com/magento/magento2/commit/b86a3940282b558ecb0363b990b6ff3dc41a61d0)

The fix will be available with the upcoming 2.2.9 release.
