### ISSUE TITLE
MFTF: Acceptance tests break the naming convention

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27503]
### Preconditions (*)
All the Magento Functional Testing Framework should follow Technical Guidelines:
https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#113-functional-testing

### Steps to reproduce (*)
1. Generate tests with `vendor/bin/mftf generate:test -f`

### Expected result (*)
1. No naming violations detected

### Actual result (*)
1. NOTICE: 165 Section name violations detected. See mftf.log for details.
1. NOTICE: 614 section element name violations detected. See mftf.log for details.
1. NOTICE: 301 data entity name violations detected. See mftf.log for details.
1. NOTICE: 15 data entity key violations detected. See mftf.log for details.
1. NOTICE: 17 action group name violations detected. See mftf.log for details.
1. NOTICE: 37 Page name violations detected. See mftf.log for details.

# Contribution

## TODO
1. Make sure that all stepKeys both for Tests and ActionGroups are camelCase (lower first letter)
1. Make sure that all Action Groups in module have `ActionGroup` suffix
1. Make sure that all Action Groups names are consistent with the filename
1. Make sure that all Action Groups names are PascalCase (upper first letter)
1. Make sure that all Test names in module have `Test` suffix
1. Make sure that all the test names are PascalCase
1. Make sure that all the test names are consistent with the filename.
1. Make sure that all Page names are Pascal Case
1. Make sure that there is only one `<page>` node in each XML file

### Backward compatibility

If you rename ActionGroup please try to keep backward compatibility:
1. Rename the ActionGroup to follow the Magento requirements
1. Create `ActionGroup/_Deprecated_/previusNameActionGroup.xml` file with contents:
```xml
<actionGroup name="previousName" extends="CurrentNameActionGroup" deprecated="Use CurrentNameActionGroup"/>
```
this way even if someone calls old Action Group name, he is going to get the notice about deprecation.

## Modules
Due to some compatibility issues and to make Code Review easier - please do your changes per module. You can find list of checkboxes underneath with list of modules that should be covered. When you start working on specific module, please check the chekbox and add the comment which module you start work. When you finish - edit your commend adding the link to PR.

Once you finished, make sure that `vendor/bin/mftf generate:test -f` does not return any errors.

### Open Source
* [ ] app/code/Magento/Catalog (6484 issues)
* [ ] app/code/Magento/Cms (2187 issues)
* [ ] app/code/Magento/Sales (1006 issues)
* [ ] app/code/Magento/Config (660 issues)
* [ ] app/code/Magento/Newsletter (631 issues)
* [ ] app/code/Magento/Shipping (604 issues)
* [ ] app/code/Magento/Store (554 issues)
* [ ] app/code/Magento/Checkout (552 issues)
* [ ] app/code/Magento/Customer (390 issues)
* [ ] app/code/Magento/Wishlist (361 issues)
* [ ] app/code/Magento/Tax (330 issues)
* [ ] app/code/Magento/ConfigurableProduct (316 issues)
* [ ] app/code/Magento/CatalogSearch (270 issues)
* [ ] app/code/Magento/User (240 issues)
* [ ] app/code/Magento/Paypal (210 issues)
* [ ] app/code/Magento/Ui (195 issues)
* [ ] app/code/Magento/SalesRule (173 issues)
* [ ] app/code/Magento/Multishipping (138 issues)
* [ ] app/code/Magento/Reports (137 issues)
* [ ] app/code/Magento/Downloadable (105 issues)
* [ ] app/code/Magento/Braintree (105 issues)
* [ ] app/code/Magento/CatalogRule (98 issues)
* [ ] app/code/Magento/Widget (90 issues)
* [ ] app/code/Magento/LayeredNavigation (90 issues)
* [ ] app/code/Magento/CatalogInventory (83 issues)
* [ ] app/code/Magento/Swatches (75 issues)
* [ ] app/code/Magento/CatalogWidget (75 issues)
* [ ] app/code/Magento/UrlRewrite (60 issues)
* [ ] app/code/Magento/Backend (57 issues)
* [ ] app/code/Magento/Translation (45 issues)
* [ ] app/code/Magento/Review (45 issues)
* [ ] app/code/Magento/CheckoutAgreements (45 issues)
* [ ] app/code/Magento/Analytics (45 issues)
* [ ] app/code/Magento/Bundle (37 issues)
* [ ] app/code/Magento/Theme (31 issues)
* [ ] app/code/Magento/Variable (30 issues)
* [ ] app/code/Magento/Persistent (30 issues)
* [ ] app/code/Magento/GroupedProduct (30 issues)
* [ ] app/code/Magento/CurrencySymbol (23 issues)
* [ ] app/code/Magento/Weee (15 issues)
* [ ] app/code/Magento/ProductVideo (15 issues)
* [ ] app/code/Magento/PageCache (15 issues)
* [ ] app/code/Magento/Integration (15 issues)
* [ ] app/code/Magento/GiftMessage (15 issues)
* [x] app/code/Magento/Captcha (15 issues)
* [x] app/code/Magento/Backup (9 issues)
* [x] app/code/Magento/Indexer (2 issues)

**Comment by konarshankar07** [comment]
I'm working on Magento/Indexer module

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27515 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [862aff3c2f432aed171f3ecafcb7b62ccd5f1731](https://github.com/magento/magento2/commit/862aff3c2f432aed171f3ecafcb7b62ccd5f1731)
 - [f0d4a6d3c71a3b23dad89aa3b03e9094b719ad6c](https://github.com/magento/magento2/commit/f0d4a6d3c71a3b23dad89aa3b03e9094b719ad6c)
 - [3286bf9d59b02b7f4d925c0badbc30875ec387e1](https://github.com/magento/magento2/commit/3286bf9d59b02b7f4d925c0badbc30875ec387e1)
 - [5cb64571b48dd835242be6ba93191fdbd5e25477](https://github.com/magento/magento2/commit/5cb64571b48dd835242be6ba93191fdbd5e25477)
 - [972812da94ea635b1e4b6fc317d3de6e481e83a2](https://github.com/magento/magento2/commit/972812da94ea635b1e4b6fc317d3de6e481e83a2)
 - [50d7d2ff6445e4b1bbf27737ee0feaa0f34bef48](https://github.com/magento/magento2/commit/50d7d2ff6445e4b1bbf27737ee0feaa0f34bef48)
 - [5eafb00a09fcb51789231fde152fe61c66f99994](https://github.com/magento/magento2/commit/5eafb00a09fcb51789231fde152fe61c66f99994)
 - [029446df74646dff63c77b773c04a0fd0f8e5f34](https://github.com/magento/magento2/commit/029446df74646dff63c77b773c04a0fd0f8e5f34)
 - [38cef7b620e96d4334aff4eaf9d21bcec7b2c93d](https://github.com/magento/magento2/commit/38cef7b620e96d4334aff4eaf9d21bcec7b2c93d)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27515 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [862aff3c2f432aed171f3ecafcb7b62ccd5f1731](https://github.com/magento/magento2/commit/862aff3c2f432aed171f3ecafcb7b62ccd5f1731)
 - [f0d4a6d3c71a3b23dad89aa3b03e9094b719ad6c](https://github.com/magento/magento2/commit/f0d4a6d3c71a3b23dad89aa3b03e9094b719ad6c)
 - [3286bf9d59b02b7f4d925c0badbc30875ec387e1](https://github.com/magento/magento2/commit/3286bf9d59b02b7f4d925c0badbc30875ec387e1)
 - [5cb64571b48dd835242be6ba93191fdbd5e25477](https://github.com/magento/magento2/commit/5cb64571b48dd835242be6ba93191fdbd5e25477)
 - [972812da94ea635b1e4b6fc317d3de6e481e83a2](https://github.com/magento/magento2/commit/972812da94ea635b1e4b6fc317d3de6e481e83a2)
 - [50d7d2ff6445e4b1bbf27737ee0feaa0f34bef48](https://github.com/magento/magento2/commit/50d7d2ff6445e4b1bbf27737ee0feaa0f34bef48)
 - [5eafb00a09fcb51789231fde152fe61c66f99994](https://github.com/magento/magento2/commit/5eafb00a09fcb51789231fde152fe61c66f99994)
 - [029446df74646dff63c77b773c04a0fd0f8e5f34](https://github.com/magento/magento2/commit/029446df74646dff63c77b773c04a0fd0f8e5f34)
 - [38cef7b620e96d4334aff4eaf9d21bcec7b2c93d](https://github.com/magento/magento2/commit/38cef7b620e96d4334aff4eaf9d21bcec7b2c93d)

The fix will be available with the upcoming 2.4.0 release.
