### ISSUE TITLE
Cannot translate meta descriptions added via XML instructions. 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#35191]
### Preconditions (*)

1. 2.4.3-p1 
2. A custom controller
3. A custom layout.xml with a meta description content
4. 2 store views

### Steps to reproduce (*)

In your layout.xml add a meta description like this 

```
<meta name="description" content="my english content" translate="content" />
```

In your `i18n/el_GR` file for example add a translation for the content.

Incidentally I've tried adding the description like this 

```
<meta name="description" content="my english content" translate="true"/>
<meta name="description" content="my english content" />
```

Neither way seems to work to make it translateable. 

However the phrase is properly collected using `i18n:collect-phrases`

### Expected result (*)

1.The content is translated

### Actual result (*)

The content is not translated

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
Hi @ioweb-gr,

In order to reproduce the issue, can you please guide me on below points.

1. Have you missed to add something after “Incidentally I've tried adding the description like this” in your comment?
2. Can you please provide some detailed information in order to investigate it further. Eg. Are you trying to see the translated content from i18n/el_GR for the added <meta> tag in .xml file? Or kindly provide all steps to reproduce in order to investigate this issue further.


Thank you in advance!

**Comment by ioweb-gr** [comment]
Hi, it seems github treated the text as tags so they wouldn't appear. I've added the content that was missing in codeblock. 

It seems the translate=true tag is not allowed for the above mentioned tags.

**Comment by lbajsarowicz** [comment]
The layout.xml meta translate="content" i18n behavior needs a live reproduction to confirm; there's been no maintainer reconfirmation since 2022, only the original reporter's evidence. Please re-QA on current 2.4-develop with the reporter's exact layout XML and locale to confirm this still occurs.
