### ISSUE TITLE
Meta tags auto generation: variables cannot be used multiple times

### ISSUE THREAD

**Issue by schnere** [magento/magento2#35670]
### Preconditions and environment

- Magento 2.3.3 / Magento 2.4.2

### Steps to reproduce

1. Execute `bin/magento config:set catalog/fields_masks/meta_keyword '{{name}}, order {{name}}'` or set manually
2. Login to Magento2 Backend
3. Create a new product
4. Set product name to "NEW PRODUCT"
5. Check meta keywords

### Expected result

The meta keywords should be set to `NEW PRODUCT, order NEW PRODUCT`

### Actual result

The meta keywords are set to `NEW PRODUCT, order {{name}}` .
So the second occurrence is not replaced as expected.

### Additional information

I think the substitution is done here?
https://github.com/magento/magento2/blob/1a7f152da7dca587e01e69012847e12cd86b75e3/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/edit.phtml#L198

So the solution would be to use `replaceAll` instead of `replace`:

```
var value = self._masks[this].replaceAll(self.varsRegexp, function(maskfieldName) {
    return $('#' + maskfieldName.slice(2, -2)).val();
});
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @schnere ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and is reproducible but however, this seems to be an expected behavior but not a bug.
As per Magento [docs1](https://docs.magento.com/user-guide/marketing/meta-data.html) and [docs2](https://docs.magento.com/user-guide/catalog/product-fields-autogenerated.html), each meta keywords tag should be unique. No URLs should have the same meta keywords value. Any phrase that you want to include in every meta description, you can type the value directly into the appropriate field.
Kindly provide reference documents / proofs that supports duplicating the same keyword for meta data to consider this as a valid bug.
Thank you.

**Comment by schnere** [comment]
Hi @engcom-November ,

thanks for your reply.
So the expected behavior if i use for example `{{manufacturer}} {{name}} - {{manufacturer}} eCommerce` would be the following output: `Adobe Magento - {{manufacturer}} eCommerce` ?

Why would someone use a variable twice not expecting it to get replaced twice?

In my opinion there are use cases to use a variable in meta tags more than once, for example as meta description:
`{{manufacturer}} {{name}} - Buy {{manufacturer}} products in our online store!`

Furthermore I think that, if this might not be a use case for anyone, it would not be a problem to replace the variable more than once. So the fix is simple and will not cause problems for anyone, but would be a solution for some?

**Comment by engcom-November** [comment]
Hi @schnere ,
Thanks for your reply. Since its not clear in Magento official docs regarding the usage of placeholders for meta data we are considering this as a feature request.
Thank you.

**Comment by engcom-Bravo** [comment]
Hi @schnere,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the sceenshots.


<img width="1438" alt="Image" src="https://github.com/user-attachments/assets/27cde4ed-c568-457d-acd1-216eaf039d16" />


The meta keywords are set to NEW PRODUCT, order {{name}}.

Hence Confirming the issue.

Thanks.
