### ISSUE TITLE
Meta Description Auto generation copying page builder tags

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#36107]
### Preconditions and environment

- 2.4.4
- Page builder on the full description (product)

### Steps to reproduce

- Add a new product
- Add some content in the full description field (pagebuilder enabled). (Edit with page builder - Add Content - Block - Drag and edit block - select block and save )
- Review the meta description
- Discover it is full of tags that should have no value

### Expected result

Clean text-only output

### Actual result

![Schermafbeelding 2022-09-07 om 14 46 30](https://user-images.githubusercontent.com/5433241/188882367-18006e18-dc4b-4427-896e-55a749293e95.png)

edit: This is the meta description field
![Schermafbeelding 2022-09-07 om 14 46 39](https://user-images.githubusercontent.com/5433241/188882406-c63794f6-a5de-407b-af69-3bf8535914f3.png)

### Additional information

The workaround is to manually update it, but chances are high it is forgotten to properly update it, thus having NOTHING would be preferred as Google is actually showing some of this garbage in it's results

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vandijkstef** [comment]
@magento give me 2.4-develop instance

**Comment by vandijkstef** [comment]
Cannot verify currently as the page builder is not allowing me to drag-in any of the (layout) elements

**Comment by vandijkstef** [comment]
@magento give me 2.4-develop instance

**Comment by vandijkstef** [comment]
> Cannot verify currently as the page builder is not allowing me to drag-in any of the (layout) elements

Tried to verify again, above issue not resolved. Can't directly find an active issue on this.

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @vandijkstef , Thank you for reporting and collaboration. 
Verified the issue on Magento 2.4-develop branch but unable to edit with Page builder for Products and this issue is being tracked in this bug: https://github.com/magento/magento2/issues/36188. 
This issue needs to be verified once above issue is resolved. Hence we are moving this issue to "On hold"
Thank you.

**Comment by chittima** [comment]
Internal team is working on the fix

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance with Page builder enabled in local instance and the issue is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/207292306-e9ddd3f8-a903-44f8-a704-dd2d32ad92b8.png)

**Comment by vandijkstef** [comment]
@magento give me 2.4-develop instance

**Comment by vandijkstef** [comment]
The issue seems 'resolved'. On my own store I get `PRODUCTTITLE - DESCRIPTION` pattern in clean. On develop instance I see `PRODUCTTITLE` (so no description).

At least it's not producing garble anymore so this issue might be up for closing

**Comment by engcom-Bravo** [comment]
Hi @vandijkstef,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/36107#issuecomment-2334181579  we are closing this issue.

Thanks.
