### ISSUE TITLE
Magento 2.4.5 - Shipment Email not showing Tracking Number, Shipping Info, Shipping Methods, Order Item

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#36426]
### Preconditions and environment

- 2.4.5
- Create an order and Send Tracking Information email

Screenshot 
https://prnt.sc/XP6t0NzYnDlq

### Steps to reproduce

1. Create an Order
2. Create New Shipment for Order
3. Add Carrier, Title, Number to New Shipment
4. Click and checked Check Email Copy of Shipment checkbox
5. Click Submit Shipment Button

### Expected result

1. Shipment email showing Carrier, Title, Number.
2. Shipment email showing Shipping Info, Shipping Methods
3. Shipment email showing Order Item

### Actual result

Shipment email is not showing Tracking Information, Shipping Info, Shipping Method, Order Item

Screenshot 
https://prnt.sc/XP6t0NzYnDlq

### Additional information

**For Shipment Tracking Number**
{{layout handle="sales_email_order_shipment_track" shipment=$shipment_id order=$order_id}}

**For Order Item**
{{layout handle="sales_email_order_shipment_items" shipment_id=$shipment_id order_id=$order_id}}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @gilbertsohal ,

We are trying to reproduce the issue in 2.4.5 magento instance...But we are not able to reproduce the issue...We are getting the expected results.

Steps:
1.Install Magento instance
2.create oder
3.checked the mail and verifying showing Carrier, Title, Number, showing Shipping Info, Shipping Methods.
4.Everything Is showing in the mail

Screenshot:
<img width="1512" alt="Screenshot 2022-11-07 at 12 09 35 PM" src="https://user-images.githubusercontent.com/60198592/200242269-9d7fb8cd-c5b1-40d8-920e-39c7c2e43b40.png">


Let us know if we missing anything!!!

Thanks!!!

**Comment by devchris79** [comment]
The layout handles were changed, I think your shipment layout handle needs to change from:

{{layout handle="sales_email_order_shipment_track" shipment=$shipment_id order=$order_id}}
to
{{layout handle="sales_email_order_shipment_track" shipment_id=$shipment_id order_id=$order_id}}

You should then find the details added.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @devchris79 ,

Thanks For your information....We are able to see the Carrier, Title, Number, showing Shipping Info, Shipping Methods.But the Reporter side is not displaying.

Thanks!!!

**Comment by engcom-Dash** [comment]
Hi @gilbertsohal ,

We are closing this issue as there has been no latest updates on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
