### ISSUE TITLE
Issuing Credit Memo (Refund) on an Order with Zero Shipping, Magento blocks this functionality.

### ISSUE THREAD

**Issue by arunmanglick-code** [magento/magento2#36638]
### Summary

**Part 1:** Recently CO Delivery Fee Implementation is taken care of across Magento connectors, where even if an Order/Invoice is with Zero/Free Shipping 0.27$ Retail Delivery Fee is charged. 

**Part 2:** Now if a seller tries to issue a Credit Memo (Refund) on the same Zero Shipping Order/Invoice, **Magento blocks this functionality.**
(Note: O Series still applies a $0.27 Retail Delivery Fee, even if the Order is having Free Shipping)	

Rationale, at the time of Invoice Creation with zero Shipping, O Series applies a $0.27 Retail Delivery Fee, and Magento stores this 0.27 Delivery Fee in Magento DB. 
Because of this, when a Credit Memo is issued against the zero-shipping order, Magento blocks the Request Payload from reaching Connector. (As Magento stored 0.27 in DB, it internally treats, it as Paid Shipping Order).
 
To make this feature work end to end, Adobe/Magento needs to do something to override this constraint.
Looking forward to your assistance to take this forward with Adobe/Magento.

Thanks 

### Examples

To be attached

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @arunmanglick-code ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with below steps performed but the issue is not reproducible.
**Steps performed:**
1. Enabled Cash on delivery payment method and free shipping delivery method from admin
2. Clear cache
3. Front end - Placed an order with COD and free shipping
4. Admin - Created invoice for the order - No retail delivery fees is charged
5. Created credit memo for the order - No issue. Credit memo created successfully.
![image](https://user-images.githubusercontent.com/60198231/208696118-35b7b0f2-e086-4ac5-812a-042363fddcc5.png)

Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by divij-satra** [comment]
Example for the Original issue:
Part 1: Recently CO Delivery Fee Implementation is taken care of across Magento connectors, where even if an Order/Invoice is with Zero/Free Shipping 0.27$ Retail Delivery Fee is charged.
PFA request_tresponse.text
[request_response.txt](https://github.com/magento/magento2/files/10276641/request_response.txt)

Part 2: Now if a seller tries to issue a Credit Memo (Refund) on the same Zero Shipping Order/Invoice, Magento blocks this.
PFA Error.JPG
![Error](https://user-images.githubusercontent.com/99982721/208877197-bfd0f4f8-f932-4166-86e4-95a777a933e9.JPG)

The error is because there is a check in vendor/magento/ module-sales/Model/Order/Creditmemo/Total/Discount.php file

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @divij-satra ,
Thank you for the response. Verified the issue again on Magento 2.4-develop instance with below steps but still unable to reproduce the issue.
1. Created a new tax rate and assigned new tax rule with Colorado address with new tax class assigned.
2. Admin - Sales - Configuration - Sales - Tax - assigned new tax class for shipping
3. Tax calculation settings set to including taxes for catalog and shipping.
4. Created a new customer with Colorado Shipping and Billing address
5. Placed an order from front end with COD
6. Created invoice
7. Created credit memo - No issue. Credit memo created successfully.
Kindly recheck the issue on Magento 2.4-develop instance and provide/elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by divij-satra** [comment]
HI @engcom-November  Did you use the free shipping?

**Comment by arunmanglick-code** [comment]
@engcom-November  - Did you try this using Vertex Tax Calc Engine? If yes, can you please share the payloads, as this issue is very evident (attached in snapshots too in an earlier thread)? 

Do you see an option where we can connect with you over the call and explain the problem statement and make best use of your time?

Thanks

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @arunmanglick-code , Thank you for the response.
Vertex tax configuration is no more available in latest Magento versions. Code of this package / extension is not part of https://github.com/magento/magento2/ repository. If the issue occurring due to 3rd party extensions / packages enabled, all questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page. Kindly recheck the behavior on Magento 2.4-develop instance without 3rd party packages and please share your slack id so that we can connect with you over the call if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment]
Hi @arunmanglick-code ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Comment by arunmanglick-code** [comment]
Thanks Team, This issue cannot be closed with chats until you agree to be on call and see the demo. Thanks again
