### ISSUE TITLE
Admin Usage Tracking causes JS error

### ISSUE THREAD

**Issue by drinkingsouls** [magento/magento2#37618]
### Preconditions and environment
 - Magento 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7
As of this morning the Knowledge Centre feature has appeared in our Magento install. I've never seen this before.
It is linked to the Admin system setting "Enable Admin Usage Tracking". This has always been enabled for us and I've never had the Knowledge Centre appear before.
 - The Knowledge Centre is causing a JS error in our console. It conflicts with some Magento Dashboard settings.
 - With Enable Admin Usage Tracking set to Yes. The "Role Resources" tab is no longer visible in User Roles.
 - Causing issues loading product grids & products also.

!https://github.com/magento/magento2/assets/45666862/dab631d3-7870-4348-933f-300e6833a9b0!

!https://github.com/magento/magento2/assets/45666862/ef5193b3-da10-4827-bb07-38c000043541!
### Steps to reproduce
 - Enable Admin Usage Tracking > Yes
 - Flush Cache
 - Knowledge Centre link appears in Dashboard
 - JS error present (console)

### Expected result

Knowledge Centre is activated in Dashboard with no errors.
### Actual result

Knowledge Centre is activated in Dashboard with errors.
### Additional information

The Knowledge Centre only appeared on our install of Magento this morning. It has never been there previously.
### Workaround

Enable Admin Usage Tracking > No
Or via CLI:
bin/magento config:set admin/usage/enabled 0;
bin/magento cache:clean;
### Release note

*No response*
### Triage and priority
 - < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by pixiemediaweb** [comment]
not just 2.4.6 - had this reported since around 11:30am (BST) on multiple sites; 2.4.3, 2.4.4, 2.4.5 etc.

**Comment by samcleathero** [comment]
Also experiencing this issue on 2.4.5-p1 - it looks like a change has been made to an externally loaded file ([here](https://assets.adobedtm.com/a7d65461e54e/37baabec1b6e/launch-177bc126c8e6.min.js)) which is causing a requireJS mismatched define error. It looks to me like this is occurring on line 22562 of the unminified file ([here](https://assets.adobedtm.com/a7d65461e54e/37baabec1b6e/launch-177bc126c8e6.js)). Disabling Admin Usage Tracking prevents this file from loading so fixes the error.

**Comment by drinkingsouls** [comment]
Yes, Enable Admin Usage Tracking set to No is a workaround for us.

**Comment by pixiemediaweb** [comment]
> @pixiemediaweb Where is this being reported?

by a number of our clients

**Comment by rbouma** [comment]
Problems with loading external JS file from Adobe causing this to not work on multiple clients on multiple Magento versions.

**Comment by willbrammer** [comment]
Experiencing this on both commerce, open-source clients varying from 2.4.4-2.4.6

Quick fix works for now

**Comment by enigmainteractiveuk** [comment]
Experiencing this issue on a range of 2.4.x Magento sites - turning off admin usage tracking also seems to have worked here. Is anybody aware of any official communications from Adobe about this issue?

**Comment by samcleathero** [comment]
> Experiencing this issue on a range of 2.4.x Magento sites - turning off admin usage tracking also seems to have worked here. Is anybody aware of any official communications from Adobe about this issue?

Confirmed in the Magento Slack that Adobe are aware and looking into it.

**Comment by rhoerr** [comment]
It also occurs on Magento Open Source 2.3.7. Any version that includes the admin usage tracking and help feature will be impacted, I expect.

**Comment by mpchadwick** [comment]
Just got off with a client who is sporadically experiencing this issue, even after we disabled admin usage tracking (somehow).

**Comment by chernenm** [comment]
@magento give me 2.4-develop instance

**Comment by glo35082** [comment]
@magento give me 2.4-develop instance

**Comment by jrswgtr** [comment]
The error is caused by an external script loaded from Adobe servers. I suspect they just changed the file recently. Multiple clients have called us with the same problem.

**Comment by xxxdepy** [comment]
I love how Adobe pushes changes out of the blue and it just breaks the admin panel completely for no apparent reason. Just Adobe things.

**Comment by drinkingsouls** [comment]
> I love how Adobe pushes changes out of the blue and it just breaks the admin panel completely for no apparent reason. Just Adobe things.

It's a pretty iconic screwup.

**Comment by jrswgtr** [comment]
I disabled the module in config.php and flushed the cache.

This way it can't be turned on again by any admin.

**Comment by jrswgtr** [comment]
> 

They're just trying to improve our experience... 🤷‍♂️🤦

**Comment by jrswgtr** [comment]
> I love how Adobe pushes changes out of the blue and it just breaks the admin panel completely for no apparent reason. Just Adobe things.

They're just trying to improve our admin user experience 😔

**Comment by jonathanribas** [comment]
Maybe they are trying to see global admin usage ahah

**Comment by FrancescNS** [comment]
Hi, here with Magento 2.4.6, I disabled in admin setup, the Analytics function and it worked for me by now.
Cannot understand how Adobe can enable this by their own without permission.
thanks!

**Comment by panthar1** [comment]
I am pretty sure this has effected every single magento site in the last few days. If not every site, every large site. Me and my co-worker spent over a day trying to figure out what could of possibly gone wrong, we looked at all possible server problems, disabled all contributed plugins, and it was still doing it,  turns out the problem is in this magento core plugin. 

You guys should really revert this unexpected change.

**Comment by drinkingsouls** [comment]
I assumed this would be revered very quickly considering that it makes the dashboard largely inaccessible.
There could at least be an announcement by Adboe with the temporary workaround.
No mention of this critical issue anywhere is very bad form.

**Comment by jrswgtr** [comment]
> I am pretty sure this has effected every single magento site in the last few days. If not every site, every large site. Me and mMe and my co-worker spent over a day trying to figure out what could of possibly gone wrong, we looked at all possible server problems, disabled all contributed plugins, and it was still doing it, turns out the problem is in this magento core plugin.y co-worker spent over a day trying to figure out what could of possibly gone wrong, we looked at all possible server problems, disabled all contributed plugins, and it was still doing it, turns out the problem is in this magento core plugin.
> 
> You guys should really revert this unexpected change.

This tutorial on how to debug the "anonymous require mismatched" error really saved my day. It lead me straight to the file of Adobe.

https://maxchadwick.xyz/blog/troubleshooting-mismatched-anonymous-define

**Comment by chernenm** [comment]
Hello everyone,

Thank you all for participating in the discussion and providing your feedback.
Adobe is currently experiencing integration issue with Admin usage data collection service, so it has been decided to turn off this functionality for the time being until the integration issue is fixed by Adobe. 
Since Admin usage data collection functionality is now turned off, all the Adobe Commerce and Magento Open Source customers should not be affected by this issue anymore with no no further actions required from customers' side.
This functionality is used by Adobe to help to improve the experience of using the Adobe Commerce Admin panel, individual users are not identified in usage data. Data collection setting can be enabled/disabled at any time from the [Admin Usage](https://experienceleague.adobe.com/docs/commerce-admin/config/advanced/admin.html?lang=en#admin-usage) configuration. 
Once the integration issue is resolved we will turn the functionality back and all the customers who has Admin Usage Tracking enabled in their configuration will get In-Product Guidance functionality back.

Please see more details about the Admin usage data collection [here](https://experienceleague.adobe.com/docs/commerce-admin/start/admin/admin.html?lang=en#usage-data-collection).

**Comment by glo35082** [comment]
@magento give me 2.4-develop instance

**Comment by xxxdepy** [comment]
> Maybe they are trying to see global admin usage ahah

One thing is for sure, the next day the analyst were like - Hey, any idea why people are refreshing the same admin page over and over again so many times?
