### ISSUE TITLE
Tracking information is currently not available.

### ISSUE THREAD

**Issue by fvlasie** [magento/magento2#38126]
### Preconditions and environment

- Magento version: 2.4.6-p3
I have set up USPS and UPS in Delivery Methods. Both are working to retrieve prices. 
I am also using ShipStation to print labels and ShipStation sends the tracking number back to Magento.

### Steps to reproduce

Open an order that has shipped under Sales>Orders
In the Shipping section click the link for "Track this shipment" after clicking "view"
The tracking pop-up will show the error "Tracking information is currently not available".

This same error shows regardless of shipping vendor, in my case USPS and UPS.

### Expected result

The tracking information should show.

### Actual result

Tracking information is currently not available.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @fvlasie 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 developer instance and the issue is reproducible. Tested with both USPS and UPS delivery methods and shipped the order. When clicked on the track the shipment link we are getting "Tracking information is currently not available". Please refer the attached screenshots.
<img width="1440" alt="Tracking" src="https://github.com/magento/magento2/assets/60198592/c6f2d2ce-c391-417d-97d0-1a4f678e665f">

**Comment by Kishorchhugani** [comment]
Any Updates regarding this issue ?
I am having same issue on Magento 246p1

**Comment by rydemods** [comment]
Also having this issue, looking for a fix 2.4.6-p3

**Comment by tkawai21** [comment]
I'm also having this issue on v2.4.5-p1 and v2.4.5-p7.

On v2.4.5-p1, if I keep reloading the tracking popup, it'll eventually show the tracking details.

**Comment by DannyDaemonic** [comment]
@engcom-Bravo For our system and [in the screenshots provided earlier](https://github.com/magento/magento2/issues/38126#issuecomment-1838655492), the issue was with USPS. Could you please try with USPS.

**Comment by tkawai21** [comment]
@engcom-Bravo I've noticed it happening with UPS and FedEx. [Here is a screencap recording of the issue with FedEx](https://www.loom.com/share/d122da0703b14f32a7b0d35b08d0a606?sid=6b6e8204-3bba-42be-9b47-d8a454a6fe1a). In it, I'm repeatedly refreshing the popup and it eventually shows the details around the 0:22 mark.

**Comment by engcom-Bravo** [comment]
Hi @tkawai21,

As we have already mentioned [here](https://github.com/magento/magento2/issues/38126#issuecomment-2137391628), we have verified the issue on 2.4 develop for UPS delivery method and the issue was not reproducible. Also we have attached the screen recording for the reference.please once reverify from your end.


https://github.com/magento/magento2/assets/51680745/d541cb88-3e39-4899-a954-602518b80b5d




Thanks.

**Comment by tkawai21** [comment]
I'm definitely still having the issue on my end. But as a workaround, I'm testing out this extension: [https://github.com/karliuka/m2.TrackingLink](https://github.com/karliuka/m2.TrackingLink)

It's looking pretty promising and we modified it so it'll also replace the tracking details with the direct Carrier's tracking link when viewing the tracking from the frontend or admin.
