### ISSUE TITLE
@todo for _getFetchUpdatesByHandleSelect

### ISSUE THREAD

**Issue by Morgy93** [magento/magento2#38492]
### Summary

There's a `@todo` since release in the `app/code/Magento/Widget/Model/ResourceModel/Layout/Update.php`.

### Examples

<img width="1286" alt="image" src="https://github.com/magento/magento2/assets/7961978/587ce5e6-7514-457b-b903-3310751bdd59">

https://github.com/magento/magento2/blob/2.4.6-p4/app/code/Magento/Widget/Model/ResourceModel/Layout/Update.php#L87

```
//@todo Why it also loads layout updates for store_id=0, isn't it Admin Store View?
//If 0 means 'all stores' why it then refers by foreign key to Admin in `store` and not to something named
// 'All Stores'?
```

### Proposed solution

Research the questions in the comment and update the code accordingly. Remove comment afterwards.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @Morgy93,

Thank you for the report!

As this `@todo` is still present, confirming this issue.

**Comment by magentoabu** [comment]
@magento I'm working on this
